export enum ConversationStatusType {
  CANCEL = 'CANCEL',
  FREELANCER_LEFT = 'FREELANCER_LEFT',
  FREELANCER_INTERESTING = 'FREELANCER_INTERESTING',
  FREELANCER_ACCEPT = 'FREELANCER_ACCEPT',
  FREELANCER_REJECT = 'FREELANCER_REJECT',
  OWNER_ACCEPT = 'OWNER_ACCEPT',
  OWNER_REJECT = 'OWNER_REJECT',
  CANCELLATION = 'CANCELLATION',
  CANCELLED = 'CANCELLED',
}
